//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Sklep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archiwum_kupionego_towaru
    {
        public long Id_kupionego_produktu { get; set; }
        public Nullable<long> Id_klienta { get; set; }
        public string Imie_i_nazwisko_klienta { get; set; }
        public string Nazwa_produktu { get; set; }
        public string Opis_produktu { get; set; }
        public string Kategoria { get; set; }
        public int Ilosc_sztuk { get; set; }
        public double Cena_zakupu { get; set; }
        public double Vat { get; set; }
        public System.DateTime Data_zakupu { get; set; }
        public byte[] Photo { get; set; }
    }
}
