//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Sklep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DaneSklepuEntities : DbContext
    {
        public DaneSklepuEntities()
            : base("name=DaneSklepuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Sprzedaż> Sprzedaż { get; set; }
        public virtual DbSet<Vat> Vat { get; set; }
        public virtual DbSet<Archiwum_kupionego_towaru> Archiwum_kupionego_towaru { get; set; }
        public virtual DbSet<Użytkownicy> Użytkownicy { get; set; }
        public virtual DbSet<Administracja> Administracja { get; set; }
    }
}
