//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Sklep
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedaż
    {
        public long Id_zakupu { get; set; }
        public long Id_klienta { get; set; }
        public long id_produktu { get; set; }
        public int Ilość_sztuk { get; set; }
        public double Cena_zakupu { get; set; }
        public System.DateTime Data_zakupu { get; set; }
    
        public virtual Produkty Produkty { get; set; }
        public virtual Użytkownicy Użytkownicy { get; set; }
    }
}
